title: Welcome!
author: Hannah Storrs
email: hannahstorrs@fakeemail.com
description: > # this means to ignore newlines until "baseurl:"
  An introduction to GitPages and trying things out here.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
